"""add passage tags

Revision ID: fd157a1fa9f2
Revises: 5162ada3a7e3
Create Date: 2026-07-15 12:00:28.978321
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fd157a1fa9f2'
down_revision: str | None = '5162ada3a7e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passages', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passages', 'tags')
    # ### end Alembic commands ###
