"""init schema

Revision ID: 5162ada3a7e3
Revises: 
Create Date: 2026-07-15 10:08:41.335235
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5162ada3a7e3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('char', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('meta', sa.String(length=80), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_slug'), 'books', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('birth_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.String(length=10), nullable=False),
    sa.Column('birth_hour', sa.Integer(), nullable=True),
    sa.Column('birth_place', sa.String(length=60), nullable=True),
    sa.Column('chart_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_birth_profiles_user_id'), 'birth_profiles', ['user_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('citation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.create_table('daily_quota',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', 'kind', name='uq_quota')
    )
    op.create_table('entitlements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('plan', sa.String(length=12), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entitlement_user_expires', 'entitlements', ['user_id', 'expires_at'], unique=False)
    op.create_table('incense_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('wish_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incense_user_status', 'incense_sessions', ['user_id', 'status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('out_trade_no', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('plan', sa.String(length=12), nullable=True),
    sa.Column('amount_fen', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('provider', sa.String(length=12), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.String(length=32), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_status', 'orders', ['status'], unique=False)
    op.create_index('ix_order_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_out_trade_no'), 'orders', ['out_trade_no'], unique=True)
    op.create_table('passages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('book_id', sa.String(length=32), nullable=False),
    sa.Column('chapter', sa.String(length=60), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('plain', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=20), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_passage_book_sort', 'passages', ['book_id', 'sort'], unique=False)
    op.create_table('qian_draws',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('hall', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=20), nullable=False),
    sa.Column('qian_slug', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qian_user_created', 'qian_draws', ['user_id', 'created_at'], unique=False)
    op.create_table('wishes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('moderation', sa.String(length=12), nullable=False),
    sa.Column('moderation_reason', sa.String(length=100), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wish_moderation_created', 'wishes', ['moderation', 'created_at'], unique=False)
    op.create_index('ix_wish_user_created', 'wishes', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wish_user_created', table_name='wishes')
    op.drop_index('ix_wish_moderation_created', table_name='wishes')
    op.drop_table('wishes')
    op.drop_index('ix_qian_user_created', table_name='qian_draws')
    op.drop_table('qian_draws')
    op.drop_index('ix_passage_book_sort', table_name='passages')
    op.drop_table('passages')
    op.drop_index(op.f('ix_orders_out_trade_no'), table_name='orders')
    op.drop_index('ix_order_user_created', table_name='orders')
    op.drop_index('ix_order_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_incense_user_status', table_name='incense_sessions')
    op.drop_table('incense_sessions')
    op.drop_index('ix_entitlement_user_expires', table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_table('daily_quota')
    op.drop_index('ix_chat_user_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_birth_profiles_user_id'), table_name='birth_profiles')
    op.drop_table('birth_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_slug'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
